### ISSUE TITLE
Is it possible to have a hassbian appdaemon script for python 3.5 or 3.6?

### ISSUE THREAD

**Issue by JuliusLedoux** [home-assistant/hassbian-scripts#154]
Make sure your running an up to date version of Hassbian before reporting a problem. If not make sure to specify what version and why so we can recreate the issue in question.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [#33](https://github.com/home-assistant/hassbian-scripts/issues/33) that's dedicated for this usage.

**Hassbian-config version (`hassbian-config -V`):**  
0.81
**Script/Suite:**
appdaemon
**Description of problem:**  
Installs appdaemon using python 3.4
**Expected:**
python 3.5 or later (as per Home assistant current version 0.66.1)

**Traceback/log (if applicable):**
```bash

```

**Additional info:**

**Comment by ludeeus** [comment]
It shuold be possible to change this.
The installer as is will use what is set for python3
for jessie this is 3.4
for stretch this is 3.5
