### ISSUE TITLE
Razberry not turning off bluetooth correctly

### ISSUE THREAD

**Issue by leothlon** [home-assistant/hassbian-scripts#158]
**Hassbian-config version (`hassbian-config -V`):**  
0.8.1
**Script/Suite:**
[Razberry](https://github.com/home-assistant/hassbian-scripts/blob/dev/package/opt/hassbian/suites/razberry.sh)
**Description of problem:**  
Does not seem to turn off bluetooth on raspberry pi 3

it should add "dtoverlay=pi3-miniuart-bt" to bottom of /boot/config.txt file (according to https://www.home-assistant.io/hassio/zwave/)
when i instead added it manually my razberry card started working

**Expected:**
properly add "dtoverlay=pi3-miniuart-bt" to bottom of /boot/config.txt file

**Traceback/log (if applicable):**
```bash

```

**Additional info:**

**Comment by ludeeus** [comment]
Can you run this and paste the result here to verify that your unit is in the scope of the script:
`grep Revision /proc/cpuinfo | cut -d: -f2 | tr -d " "`

**Comment by leothlon** [comment]
it gives me:

a02082

**Comment by ludeeus** [comment]
Thanks, then it's supposed to work :)
Will do some troubleshooting later today :)
