### ISSUE TITLE
install ha failed

### ISSUE THREAD

**Issue by morestart** [home-assistant/hassbian-scripts#161]
Make sure your running an up to date version of Hassbian before reporting a problem. If not make sure to specify what version and why so we can recreate the issue in question.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [#33](https://github.com/home-assistant/hassbian-scripts/issues/33) that's dedicated for this usage.

**Hassbian-config version (`hassbian-config -V`):**  

**Script/Suite:**

**Description of problem:**  
when i use sudo hassbian-config upgrade homeassistant=0.65.6 i got a suite homeassistant=0.65.6 doesn't exist. error
**Expected:**

**Traceback/log (if applicable):**
```bash
suite homeassistant=0.65.6 doesn't exist.

```

**Additional info:**

**Comment by ludeeus** [comment]
You need to upgrade hassbian-config to the pre-release version for that to be possible.
<https://github.com/home-assistant/hassbian-scripts/releases/tag/v0.9.0>
