### ISSUE TITLE
Getting the RC version?

### ISSUE THREAD

**Issue by ferazambuja** [home-assistant/hassbian-scripts#162]
Make sure your running an up to date version of Hassbian before reporting a problem. If not make sure to specify what version and why so we can recreate the issue in question.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [#33](https://github.com/home-assistant/hassbian-scripts/issues/33) that's dedicated for this usage.

**Hassbian-config version (`hassbian-config -V`):**  

**Script/Suite:**

**Description of problem:**  

**Expected:**

**Traceback/log (if applicable):**
```bash

```

**Additional info:**
Is there any way to include the rc branch?

**Comment by ludeeus** [comment]
@ferazambuja  yes, but it requires version 0.9.0 og `hassbian-config`
Once you have that you can run:
`sudo hassbian-config upgrade homeassistant --beta`
