### ISSUE TITLE
Unable to get Beta version

### ISSUE THREAD

**Issue by funnybutrandom** [home-assistant/hassbian-scripts#164]
When running hassbian-script 0.9.0 the script is unable to get the beta version of home assistant, it seems to be an issue with getting the current beta version from the json file
<img width="579" alt="screen shot 2018-05-05 at 23 15 39" src="https://user-images.githubusercontent.com/2676440/39667988-68982f62-50ba-11e8-8a66-de09ab7b24d0.png">

**Comment by ludeeus** [comment]
This got broken after pypi changed their domain and structure of the json file.
I'm working on a fix for it.

**Comment by funnybutrandom** [comment]
@ludeeus The upgrade script now fails at checking current version:
<img width="563" alt="screen shot 2018-05-07 at 22 10 02" src="https://user-images.githubusercontent.com/2676440/39725382-6f894146-5243-11e8-95bf-edb7f0fa233b.png">

**Comment by ludeeus** [comment]
It did not fail, it just checked the version against the wrong branch.
