### ISSUE TITLE
Install Python package hassbian

### ISSUE THREAD

**Issue by balloob** [home-assistant/hassbian-scripts#17]
To detect that we're running hassbian, please install `hassbian` into the image: `pip3 install hassbian==0.1`

Make sure you pin the version so that we know which version shipped with which Hassbian image and we can notify the user as such if they need to upgrade.

**Comment by balloob** [comment]
Source is here: https://github.com/home-assistant/python-hassbian

**Comment by Landrash** [comment]
Could you make a change to the hassbian package to require home-assistant package?
That way we still only install one package and that package installs whatever python packages we want on the pi's?

**Comment by balloob** [comment]
I don't like that - the package can run without Home Assistant and by depending on Home Assistant we might block any other tools that people want to write for Hassbian management.

What is wrong with running `pip3 install hassbian-scripts home-assistant` ?

**Comment by Landrash** [comment]
Your right. I'll implement your solution :smiley:

**Comment by Landrash** [comment]
Implemented in dev branch.
