### ISSUE TITLE
Cloud9 - workspace directory is (possibly) incorrect

### ISSUE THREAD

**Issue by ohadbenita** [home-assistant/hassbian-scripts#177]
When installing Cloud9 using the scripts the default workspace directory is /home/homeassistant
Since ./.homeassistant directory is hidden (starts with a period) it doesn't show in searches made with Ctrl+E in C9

**Comment by ohadbenita** [comment]
Is there any way to apply this fix now ?

Thanks !

**Comment by ludeeus** [comment]
@ohadbenita _if_ the fix gets merged in dev you can download the dev version off hassbian-config
```
sudo hassbian-config upgrade hassbian-script --dev
```
and then run:
```
sudo hassbian-config install cloud9 --force
```

or look through the changes and apply them manually.

**Comment by ohadbenita** [comment]
Sorry to bug - is there any chance this will be merged any time soon ? thanks @ludeeus and all for the hard work
