### ISSUE TITLE
Add script "update-home-assistant.sh"

### ISSUE THREAD

**Issue by oeysteinhansen** [home-assistant/hassbian-scripts#22]
Add a script to update to the last version of Home Assistant. 
Running the commands (from [Home Assistant IO docs](https://home-assistant.io/docs/hassbian/common-tasks/) ) :  
> $ sudo systemctl stop home-assistant@homeassistant.service 
> $ sudo su -s /bin/bash homeassistant
> $ source /srv/homeassistant/bin/activate
> $ pip3 install --upgrade homeassistant
> $ exit
> $ sudo systemctl start home-assistant@homeassistant.service

Or some other appropriate combination of commands.
For a Home Assistent user like me. It is allways a pain to find which update procedure to use from the wiki.

**Comment by Landrash** [comment]
Already a pull request open for this here https://github.com/home-assistant/hassbian-scripts/pull/15
Currently the tools we are using won't allow this. Have a look at the dev branch if your curios.
