### ISSUE TITLE
Incorrect permissionson /srv/homeassistant

### ISSUE THREAD

**Issue by gpbenton** [home-assistant/hassbian-scripts#221]
Make sure your running an up to date version of Hassbian before reporting a problem. If not make sure to specify what version and why so we can recreate the issue in question.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [#33](https://github.com/home-assistant/hassbian-scripts/issues/33) that's dedicated for this usage.

**Hassbian-config version (`hassbian-config -V`):**  
image_2018-10-27-Hassbian
**Script/Suite:**
homeassistant
**Description of problem:**  
According to this thread https://community.home-assistant.io/t/home-assistant-service-not-starting-on-new-hassbian-install/77869 
and this thread 
https://community.home-assistant.io/t/services-home-assistant-homeassistant-failed/78681

A number of new installers are experiencing incorrect permissions on /srv/homeassistant

**Expected:**

**Traceback/log (if applicable):**
```bash

```

**Additional info:**

**Comment by Landrash** [comment]
Fixed with #221 . thanks for the report
