### ISSUE TITLE
Add script "update.sh" or "update-hassbian-scripts.sh"

### ISSUE THREAD

**Issue by oeysteinhansen** [home-assistant/hassbian-scripts#23]
Add a script to update to the last version of hassbian-scripts.
Running the commands ( from [Home Assistant IO docs](https://home-assistant.io/docs/hassbian/upgrading/) ) :

> $ cd /home/pi/hassbian-scripts
> $ git pull

Or some other appropriate combination of commands.
For a Home Assistent user like me. It is allways a pain to find all the right commands from the wiki.

**Comment by Landrash** [comment]
In the dev branch we are moving away from the scripts being in a git repo.
They are pre-installed on the image with a debian package and hopefully we will get that on a mirror in some time.
That would make this upgrade process as easy as `apt-get upgrade -y`.
