### ISSUE TITLE
Home Assistant does not install after Hassbian finishes.

### ISSUE THREAD

**Issue by dsldsl1980** [home-assistant/hassbian-scripts#232]
Home assistant doesn't attempt to install and if you try to manually install it, permissions are not set right.

Make sure your running an up to date version of Hassbian before reporting a problem. If not make sure to specify what version and why so we can recreate the issue in question.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [#33](https://github.com/home-assistant/hassbian-scripts/issues/33) that's dedicated for this usage.

**Hassbian-config version (`hassbian-config -V`):**  

**Script/Suite:**

**Description of problem:**  

**Expected:**

**Traceback/log (if applicable):**
```bash

```

**Additional info:**

**Comment by ludeeus** [comment]
It fails because a timeout, there is an active PR to fix that https://github.com/home-assistant/hassbian-scripts/pull/231


Until then you can force the HA install with:

```bash
sudo hassbian-config install homeassistant --force
```
