### ISSUE TITLE
PiHole issue on DNS

### ISSUE THREAD

**Issue by fuzunspm** [home-assistant/hassbian-scripts#239]
**Hassbian-config version (`hassbian-config -V`):**  
0.11.1
**Script/Suite:**
PiHole
**Description of problem:**  
Can't access any nameserver including Home Assistante frontend
**Expected:**
Able to access web

**Additional info:**
After i installed pihole without any error, it works but i can't connect anything with domain name including home assistant frontend. I added 8123 port to the iptables and and check resolv file but everything looks good. I setup my router to point it to pihole on DNS. I can access web on my PC but can't ping google.com on pihole raspberry pi3 or access home assistant frontend. It works on 3G or external connections btw.

**Comment by Landrash** [comment]
The pi-hole script just runs the pi-hole installer. I believe you can get better support in their community with your pi-hole setup.
