### ISSUE TITLE
 zigbee2mqtt install script outdated node version.

### ISSUE THREAD

**Issue by JLFN** [home-assistant/hassbian-scripts#240]
Old version for node for zigbee2mqtt.sh Line 19
https://github.com/home-assistant/hassbian-scripts/blob/53d65eaacc325905937080c46705650f34e386b2/package/opt/hassbian/suites/zigbee2mqtt.sh#L19

It should be 
  curl -sL https://deb.nodesource.com/setup_10.x | bash -

See manual .
https://koenkk.github.io/zigbee2mqtt/getting_started/running_zigbee2mqtt.html

**Comment by Landrash** [comment]
Fixed in 9d525c5
