### ISSUE TITLE
Issue when removing cloud9

### ISSUE THREAD

**Issue by ruggi99** [home-assistant/hassbian-scripts#241]
**Hassbian-config version (`hassbian-config -V`):**  
0.11.1
**Script/Suite:**
cloud9
**Description of problem:**  
When I remove the cloud9 suite with hassbian-config, I see that in file:
<pre>
/srv/homeassistant/hassbian/control/cloud9
</pre>
there is still
<pre>
SCRIPTSTATE=installed
</pre>
So, when I want to reinstall cloud9, hassbian-config tries to update it instead of installing it.
I have to do:
<pre>
sudo hassbian-config install cloud9 --force
</pre>
to make it install

**Comment by ludeeus** [comment]
That is correct, it will be resolved in 0.12.0

**Comment by ruggi99** [comment]
Ok, thank you
