### ISSUE TITLE
 suite custom-component-store doesn't exist - And what is "Manager"?

### ISSUE THREAD

**Issue by imbaimbaimba** [home-assistant/hassbian-scripts#242]
The custom-component store is not working for me, it that to be expected? I have updated hassbian, hassbian-scripts, etc., but still no luck. I just get:
suite custom-component-store doesn't exist.

Also, anyone that can explain what the "Manager" script is for? I don't exactly understand what suites are?

**Comment by ludeeus** [comment]
`custom-component store` and `manager` will not be available before the next version of `hassbian-config`

The `manager` script installs a web tool to manage your suites (suites are our pre-build install/upgrade scripts)
You can see a "demo" on how it works in the PR that added it <https://github.com/home-assistant/hassbian-scripts/pull/233>
