### ISSUE TITLE
can i set password for cloud 9

### ISSUE THREAD

**Issue by xkinghost** [home-assistant/hassbian-scripts#250]
I am using cloud9. it very nice
but anyone can direct use this, can i set  password for cloud 9 UI

**Comment by ludeeus** [comment]
Change this argument on line 7 in the service file:
```
-a :
```
to:
```
-a username:password
```

**Comment by xkinghost** [comment]
can you help me with detail ?

pi@hassbian:~ $ sudo -u cloud9 -H -s
sudo: unknown user: cloud9
sudo: unable to initialize policy plugin
pi@hassbian:~ $ -a
-bash: -a: command not found
pi@hassbian:~ $ sudo -u homeassistant -H -s
homeassistant@hassbian:/home/pi $ cloud9
bash: cloud9: command not found
homeassistant@hassbian:/home/pi $ source /srv/homeassistant/bin/activate
(homeassistant) homeassistant@hassbian:/home/pi $ cloud9
bash: cloud9: command not found
(homeassistant) homeassistant@hassbian:/home/pi $

**Comment by ludeeus** [comment]
The service file is located here  `/etc/systemd/system/cloud9@homeassistant.service`

**Comment by xkinghost** [comment]
thanks it worked
