### ISSUE TITLE
sudo: unable to resolve host hassbian

### ISSUE THREAD

**Issue by starlifter** [home-assistant/hassbian-scripts#27]
I got the error "sudo: unable to resolve host hassbian" every time I issued a sudo command after installation. I believe this was because the install failed to update /etc/hosts with the hostname it assigned

**Comment by Landrash** [comment]
It's been fixed in the dev repo for quite a while and if you download the pre-release image instead your won't have this problem.

The error in question is just and annoyance and won't cause any problems.

**Comment by starlifter** [comment]
Thanks for Hassbian and the response. I'm glad to hear it has already been addressed.
