### ISSUE TITLE
duckdns hook.sh 404

### ISSUE THREAD

**Issue by calebmah** [home-assistant/hassbian-scripts#288]
## Hassbian-config version
0.12.0

## Suite name
duckdns

## Description of problem
`hook.sh` file is not being created properly. Line 52 `curl -so ./hook.sh https://raw.githubusercontent.com/home-assistant/hassbian-scripts/dev/package/opt/hassbian/suites/files/ssl_hook.sh` returns a 404.

**Comment by ludeeus** [comment]
That is correct, it was a bad design, it has been corrected in dev.
Install the dev version of hassbian-config or:
In `/opt/hassbian/suites/duckdns.sh`
Change line 52 from:
```
  curl -so ./hook.sh https://raw.githubusercontent.com/home-assistant/hassbian-scripts/dev/package/opt/hassbian/suites/files/ssl_hook.sh
```
to:
```
  curl -so ./hook.sh https://raw.githubusercontent.com/home-assistant/hassbian-scripts/master/package/opt/hassbian/suites/files/ssl_hook.sh
```
