### ISSUE TITLE
wpa_supplicant.conf not loading ?

### ISSUE THREAD

**Issue by ErikSiemens** [home-assistant/hassbian-scripts#294]
Hello,

I downloaded this version as being the last one becourse I had problems with the last one (23-3-2019 I think).
But this version seems not to load wpa_supplicant.conf
With this version I have no internet connection to my RP3+ what so ever

Kind regards

**Comment by ludeeus** [comment]
Try the image from 14-04-2019

**Comment by ErikSiemens** [comment]
Thats the version where I have this problem with
I am using version 14-4-2019
With version I thing 23-3-2019 (or close to that) I did not have this problem (but an other, after install)

**Comment by ludeeus** [comment]
I have been using Wifi on that without any issues 🤷‍♂ 
Can you post your `wpa_supplicant.conf` file?

**Comment by ErikSiemens** [comment]
It's still the same as with ver 23-3-2019

country=NL
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="[SSID]"
    psk="[paswd]"
}

**Comment by ErikSiemens** [comment]
I see there is a new release, ver 14-5-2019.
I give this one a try

**Comment by Landrash** [comment]
@ErikSiemens Any update?

**Comment by ErikSiemens** [comment]
Sorry, I could not find back this post.
After update it seems to work OK
Thanx for you help !
