### ISSUE TITLE
Issue tracking for Hassbian based on Debian Buster

### ISSUE THREAD

**Issue by Landrash** [home-assistant/hassbian-scripts#297]
## Issue tracking for Hassbian based on Debian Buster

This issue is for tracking known problems with Hassbian image based on  Debian Buster.

### Related issues
 * Debian Buster: Mosquitto #267
 * Debian Buster: Pi-Hole #286

**Comment by LeonDragon** [comment]
Problem in release version 2019-05-14. The hass service is not intatiated at the first boot. The wifi connectivity also have some problem even setup the config file as in https://www.home-assistant.io/docs/installation/hassbian/installation/

**Comment by Landrash** [comment]
Hass service isn't enabled until the installer has run it's course. (30 min on a base install)

Wifi problem is an upstream problem that I don't have a simple solution for currently.

**Comment by syabruk** [comment]
Missing release of deCONZ: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1558

**Comment by Landrash** [comment]
@SeTeM Deconz-rest-plugin don't have a release for buster it seems. This isn't related to the Hassbian image and nothing we can or will correct.

**Comment by LeonDragon** [comment]
There is a conflict when using zigbee2mqtt in this version. In details, the version of node.js needs to be downgraded to v10.x  to compatible with this component. the npm commands seem to have some error?

**Comment by flex-0** [comment]
Deconz is not working with buster by now. Is there a workaround for now or do we have to wait until Deconz releases a new version?

**Comment by Landrash** [comment]
I've never used deconz so I think that's something you'll have to ask
Deconz about.

Hassbian is just a generic Debian Buster under it all.

**Comment by Landrash** [comment]
https://www.home-assistant.io/blog/2019/10/26/rip-hassbian/
