### ISSUE TITLE
documentation - 404

### ISSUE THREAD

**Issue by jooka1978** [home-assistant/hassbian-scripts#298]
The documentation for the content in this repository can be found here: https://home-assistant.github.io/hassbian-scripts/
It gives 404.

**Comment by robmarkcole** [comment]
As do the children https://github.com/home-assistant/hassbian-scripts/blob/master/docs/webterminal.md

**Comment by Landrash** [comment]
Should be addressed but waiting for results of update.

**Comment by Landrash** [comment]
Fixed https://home-assistant.github.io/hassbian-scripts/
