### ISSUE TITLE
Using hassbian script to upgrade python from 3.7.3rc1

### ISSUE THREAD

**Issue by nelbs** [home-assistant/hassbian-scripts#302]
Recently I did a fresh install of hassbian. I downloaded the latest image [v1.6/image_2019-05-14-Hassbian.zip). I did not noticed that this version is based on debian buster which is not released yet.

My question is if I can use the hassbian script to update from python 3.5 to the latest stable version (as mentioned in the release notes of HA 0.94) because I am already on python 3.7.3rc1.

thanks

**Comment by ludeeus** [comment]
There is no need for you to do anything :)
3.7.3RC1 is virtually the same as 3.7.3

For the image based on Buster HA is already running under 3.7+ 👍
