### ISSUE TITLE
Debian Buster: Tor Onion Service

### ISSUE THREAD

**Issue by akacruel** [home-assistant/hassbian-scripts#310]
## Hassbian-config version
0.13.1
## Description of problem
Tor doesn`t start after installation. On the previous version of Hassbian (Stretch) it worked without any problem.
## Expected result

```text

```

## Traceback/log
$ sudo more /var/lib/tor/homeassistant/hostname
more: stat of /var/lib/tor/homeassistant/hostname failed: No such file or directory
**Additional info:**

```text


```

**Comment by ludeeus** [comment]
`tor` is not provided as part of `hassbian-scripts`, you should open a bug report with the tor project.
