### ISSUE TITLE
wrong glibc version after update

### ISSUE THREAD

**Issue by m0rph13** [home-assistant/hassbian-scripts#313]
## Hassbian-config version

0.13.1

## Suite name

?

## Description of problem

```
After running the script 
sudo hassbian-config upgrade python
to upgrade Python to the lastest stable version, Home assistant does not start.
```

## Expected result

```
Home assistant should start successfully
```

## Traceback/log

```bash

2019-08-03 12:12:35 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=16 from 2019-08-03 10:10:13.284521)
2019-08-03 12:12:36 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Z-Wave for zwave
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 153, in async_setup
    hass, self)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/zwave/__init__.py", line 265, in async_setup_entry
    from openzwave.option import ZWaveOption
  File "/srv/homeassistant/lib/python3.7/site-packages/openzwave/option.py", line 29, in <module>
    import libopenzwave
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /srv/homeassistant/lib/python3.7/site-packages/libopenzwave.cpython-37m-arm-linux-gnueabihf.so)
```

**Comment by hiwok** [comment]
Hello,

Same problem here. Please find my solution :

Verify GLIBC_2.28 is not present : 
strings /lib/arm-linux-gnueabihf/libc.so.6 | grep GLIBC

Add testing in your sources :
"deb http://http.debian.net/debian/ testing main contrib non-free" >> /etc/apt/sources.list

Upgrade your system (Care, it's a testing package)!
sudo apt-get update
sudo apt-cache search lib6c
sudo apt-get -f install libc6

strings /lib/arm-linux-gnueabihf/libc.so.6 | grep GLIBC_2.28

It's now present.

**Comment by kwende** [comment]
Running 

`"deb http://http.debian.net/debian/ testing main contrib non-free" >> /etc/apt/sources.list`

Results in:
`bash: deb http://http.debian.net/debian/ testing main contrib non-free: No such file or directory`

**Comment by Nocsaron** [comment]
The command should be
 `echo "deb http://http.debian.net/debian/ testing main contrib non-free" >> /etc/apt/sources.list`

You can also manually add the line in the file using vim or your favorite text editor

**Comment by piet206** [comment]
Thanks, that worked for me.

**Comment by stephanvierkant** [comment]
I've ran into the same problem after updating Homeassistant. I've upgraded to Debian 10, which has GLIBC_2.28

**Comment by Landrash** [comment]
https://www.home-assistant.io/blog/2019/10/26/rip-hassbian/
