### ISSUE TITLE
problem on version update

### ISSUE THREAD

**Issue by platini76** [home-assistant/hassbian-scripts#317]
after update from 0.96.3 to 0.96.5 and again to 0.97 I have wrong version displayed

someone know how to solve?

![a9161356dc46b6dddc066702b82b3048d897fde0](https://user-images.githubusercontent.com/10352902/64339020-55788b80-cfe3-11e9-8688-7e22d9257940.png)
![23ceec7a4ad5dcc93955ea023aa6208ade4e555b_2_1380x542](https://user-images.githubusercontent.com/10352902/64339042-66c19800-cfe3-11e9-920c-247feab73160.png)

**Comment by ludeeus** [comment]
You probably have 2 instances of Home Assistant installed.
Please use our forum, or Discord for support :)

https://www.home-assistant.io/help/#communication-channels

**Comment by platini76** [comment]
I don't know if I have two instances but... I use hassbian-config update for 1 year without issue... then 1 month ago it happens... I  think this is a problem of the script...
I tried to use the forum but they say don't use this script...
https://community.home-assistant.io/t/homeassistant-version-wrong-displayed/130667
