### ISSUE TITLE
Symlinks openzwave not working

### ISSUE THREAD

**Issue by flyingdutchman31** [home-assistant/hassbian-scripts#32]
The symlinks are only for ozw_config, but ozwcp and homeassistant still uses folder config. I executed the below statements and it worked for me. I also had to execute the chown with a sudo, cause I got an exit denied.

echo "Linking ozwcp config directory"
cd /srv/homeassistant/src/open-zwave-control-panel
ln -sd /srv/homeassistant/lib/python3.*/site-packages/python_openzwave/ozw_config
ln -sd /srv/homeassistant/lib/python3.*/site-packages/python_openzwave/ozw_config config
sudo chown -R homeassistant:homeassistant /srv/homeassistant/src

echo "Linking Home Assistant OpenZWave config directory"
cd /home/homeassistant/.homeassistant
sudo -u homeassistant ln -sd /srv/homeassistant/lib/python3.*/site-packages/python_openzwave/ozw_config
sudo chown -R homeassistant:homeassistant /home/homeassistant/.homeassistant
sudo ln -sd /srv/homeassistant/lib/python3.*/site-packages/python_openzwave/ozw_config config
sudo chown -R homeassistant:homeassistant /srv/homeassistant/src

**Comment by Landrash** [comment]
Fixed in dev but leaving this open until I've verified it on an actual pi
