### ISSUE TITLE
Script of OpenZwave reinstalls again !!

### ISSUE THREAD

**Issue by vincegre** [home-assistant/hassbian-scripts#35]
Hi

Downloaded the latest Hassbian image on HA website, burn on sd card then installed on my PI, then installed Mosquitto server and then Zwave-pip. Once done, I add in my configuration.yaml declaration of ZWave with just the USB port it's plugged in !
I then restart HA and it triggers again the installation of ZWave-pip and then HA complains Zwave is not working and need to be fixed !
Did the whole process two times and still the same :(

Vincèn

**Comment by Landrash** [comment]
Sadly enough I don't  have a good workaround currently. 
OpenZWave currently is installed by HA when the Z-Wave component is used so the install script for Z-Wave shouldn't be needed anymore :)
