### ISSUE TITLE
Turn into hotspot when not connected to internet

### ISSUE THREAD

**Issue by balloob** [home-assistant/hassbian-scripts#8]
It would be cool if we could have the Raspberry Pi turn itself into a hotspot when it is not connected to wifi and allow the user to configure it.

There is a tool available called [resin-wifi-connect](https://github.com/resin-io/resin-wifi-connect) that does this. The people from Radiodan have been able to get it working on a Debian Jessie image and have detailed instructions on how to get it running: http://andrewnicolaou.co.uk/posts/2015/resin-wifi-connect-without-docker

It would be awesome if we could get this working too.

**Comment by Landrash** [comment]
Moved to 0.9.0 Project.
