### ISSUE TITLE
Some thoughts for the future.

### ISSUE THREAD

**Issue by ludeeus** [home-assistant/hassbian-scripts#80]
First of all I would like to state that this is not an **issue** but my personal opinions and ideas.

### Naming
I strongly belive that the package created with this repo should be called `hassbian-config` this is the name most users will think the name is, since all commands are `hassbian-confing *some_comand*`
For new install this should not be an issue, but for existing it will require manually removing the old package.

### Versioning
Based on inspiration from https://semver.org/
I think that 'hassbian-scripts' should follow an MAJOR.MINOR.PATCH versioning scheme.
```
MAJOR version when you make incompatible API changes.
MINOR version when you add functionality in a backwards-compatible manner.
PATCH version when you make backwards-compatible bug fixes.
```
##### 1.x.x - MAJOR 
Will include changes to core functionality, renaming (for instance to `hassbian-config'`), and other changes that will result in users having to take extra steps to custom scripts for `hassbian-scripts` or extra steps to update.

##### x.1.x - MINOR
Will include new functionality that wont break workflows, new scripts, or removal of scripts no longer applicable. 

##### x.x.1 - PATCH
Will include stuff like minor corrections/additions to existing packages (scripts), typos and hotfixes.

### Distribution
Lately I have been toying around with an distribution channel for `hassbian-scripts` that would streamline the install/update process.
The package itself is hosted on github, and installation/upgrade through `apt install/upgrade`.
I have an working demo/sample for this hosted [here.](https://github.com/ludeeus/hassbian-repository)
Updates to that repo is generated using this [script.](https://gist.github.com/ludeeus/0c5d28aa33a37d187b5fd05fbcede8ef)
That script also generate an changelog based on milestones used in `home-assistant/hassbian-scripts`.

#### Changelog*
For the changelog part of that workflow should work, there has to be an milestone matching that release, and PR's included (that should show up in an changelog) in that release needs to be tagged with matching milestone.
The change log, will include PR# (w/hyperlink), title of the PR, and the contributor(w/hyperlink)

**Comment by Landrash** [comment]
Items moved to Project for v0.8.0 https://github.com/home-assistant/hassbian-scripts/projects/1
