### ISSUE TITLE
Upgrade script gives wrong discord channel?

### ISSUE THREAD

**Issue by DubhAd** [home-assistant/hassbian-scripts#92]
As reported in Discord by eFlame, the upgrade script tells people:

_If you have issues with this script, please say something in the #Hassbian channel on Discord_

Except, there is no such channel, and the closest is the channel for Hassbian development, leading to general support questions being asked in the dev channel...

**Comment by Landrash** [comment]
@DubhAd Channel name was change to reflect that it's not for general support. Should probably be fixed in the scripts also.

**Comment by ludeeus** [comment]
Most scripts I dev now has the new channel name, and the line in question is:
"If you have issues with this script, please say something in the #devs_hassbian channel on Discord." I believe that this is the way to have it, if there is an issue with the scripts that channel would be the correct place other than here to report it.
